#version 460 core

#extension GL_EXT_relaxed_block_layout : enable
#extension GL_EXT_scalar_block_layout : enable

struct S_0 {
    int i;
    vec3 j;
};

struct S_1 {
    int i;
    int j;
    vec3 k;
};

struct S_2 {
    int i;
    dvec3 d;
};

layout(binding = 0, scalar, relaxed) buffer SSBO {
    vec3    v3_0;
    vec3    v3_1;
    int     i_0;
    uvec2   uv2_0;
    double  d_0;
    vec2    v2_arr_0[2];
    float   f_0;
    vec3    v3_arr_0[2];
    int     i_1;
    dvec3   dv3_0;
    float   f_1;
    vec2    v2_0;
    float   f_2;
    S_0     s0_0;
    mat2x2  m22_col_0;
    S_0     s0_1;
    mat3x3  m33_col_0;
    S_0     s0_2;
    mat2x3  m23_col_0;
    S_0     s0_3;
    mat3x2  m32_col_0;
    S_0     s0_4;
    mat4x2  m42_col_0;
    S_0     s0_5;
    mat4x3  m43_col_0;
    S_0     s0_6;
    mat4x4  m44_col_0;
    S_0     s0_7;
    mat3x4  m34_col_0;
    S_0     s0_8;
    mat2x4  m24_col_0;
    S_0     s0_9;
    layout(row_major) mat2x2  m22_row_0;
    S_0     s0_10;
    layout(row_major) mat3x3  m33_row_0;
    S_0     s0_11;
    layout(row_major) mat2x3  m23_row_0;
    S_0     s0_12;
    layout(row_major) mat3x2  m32_row_0;
    S_0     s0_13;
    layout(row_major) mat4x2  m42_row_0;
    S_0     s0_14;
    layout(row_major) mat4x3  m43_row_0;
    S_0     s0_15;
    layout(row_major) mat4x4  m44_row_0;
    S_0     s0_16;
    layout(row_major) mat3x4  m34_row_0;
    S_0     s0_17;
    layout(row_major) mat2x4  m24_row_0;
    S_0     s0_18;
    S_0     s0_arr_0[2];
    S_0     s0_19;
    S_1     s1_0;
    S_2     s2_0;
    S_1     s1_arr_0[2];
    S_2     s2_arr_0[52];
    S_0     s0_20;
} ssbo;

layout(binding = 1, scalar, relaxed) uniform UBO {
    vec3    v3_0;
    vec3    v3_1;
    int     i_0;
    uvec2   uv2_0;
    double  d_0;
    vec2    v2_arr_0[2];
    float   f_0;
    vec3    v3_arr_0[2];
    int     i_1;
    dvec3   dv3_0;
    float   f_1;
    vec2    v2_0;
    float   f_2;
    S_0     s0_0;
    mat2x2  m22_col_0;
    S_0     s0_1;
    mat3x3  m33_col_0;
    S_0     s0_2;
    mat2x3  m23_col_0;
    S_0     s0_3;
    mat3x2  m32_col_0;
    S_0     s0_4;
    mat4x2  m42_col_0;
    S_0     s0_5;
    mat4x3  m43_col_0;
    S_0     s0_6;
    mat4x4  m44_col_0;
    S_0     s0_7;
    mat3x4  m34_col_0;
    S_0     s0_8;
    mat2x4  m24_col_0;
    S_0     s0_9;
    layout(row_major) mat2x2  m22_row_0;
    S_0     s0_10;
    layout(row_major) mat3x3  m33_row_0;
    S_0     s0_11;
    layout(row_major) mat2x3  m23_row_0;
    S_0     s0_12;
    layout(row_major) mat3x2  m32_row_0;
    S_0     s0_13;
    layout(row_major) mat4x2  m42_row_0;
    S_0     s0_14;
    layout(row_major) mat4x3  m43_row_0;
    S_0     s0_15;
    layout(row_major) mat4x4  m44_row_0;
    S_0     s0_16;
    layout(row_major) mat3x4  m34_row_0;
    S_0     s0_17;
    layout(row_major) mat2x4  m24_row_0;
    S_0     s0_18;
    S_0     s0_arr_0[2];
    S_0     s0_19;
    S_1     s1_0;
    S_2     s2_0;
    S_1     s1_arr_0[2];
    S_2     s2_arr_0[52];
    S_0     s0_20;
} ubo;

void main() {
    ssbo.i_0 = ubo.i_0;
}